# Generated by Django 5.2.7 on 2025-11-01 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title displayed on the page and used to generate the slug.', max_length=200, unique=True)),
                ('slug', models.SlugField(help_text="The URL path for the page (e.g., 'about' results in /about/). Must be unique.", max_length=200, unique=True)),
                ('content', models.TextField(help_text='The main body content of the page (supports HTML/Markdown).')),
                ('seo_description', models.CharField(blank=True, help_text='A brief, compelling description for search engine results (meta description).', max_length=160)),
                ('seo_keywords', models.CharField(blank=True, help_text='Comma-separated list of primary keywords (meta keywords).', max_length=255)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dynamic Page',
                'verbose_name_plural': 'Dynamic Pages',
                'ordering': ['title'],
            },
        ),
    ]
