# Generated by Django 5.2.7 on 2025-10-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('gender', models.CharField(blank=True, choices=[('Men', 'Men'), ('Women', 'Women'), ('Unisex', 'Unisex')], max_length=10, null=True)),
                ('launch_year', models.IntegerField(blank=True, null=True)),
                ('notes_top', models.TextField(blank=True, null=True)),
                ('notes_middle', models.TextField(blank=True, null=True)),
                ('notes_base', models.TextField(blank=True, null=True)),
                ('longevity', models.CharField(blank=True, max_length=100, null=True)),
                ('sillage', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='perfume_images/')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
