# Generated by Django 5.2.7 on 2025-10-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfume',
            old_name='notes_base',
            new_name='base_notes',
        ),
        migrations.RenameField(
            model_name='perfume',
            old_name='longevity',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='perfume',
            old_name='sillage',
            new_name='mainaccord1',
        ),
        migrations.RenameField(
            model_name='perfume',
            old_name='notes_middle',
            new_name='middle_notes',
        ),
        migrations.RenameField(
            model_name='perfume',
            old_name='launch_year',
            new_name='rating_count',
        ),
        migrations.RenameField(
            model_name='perfume',
            old_name='notes_top',
            new_name='top_notes',
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='image',
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='price',
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='slug',
        ),
        migrations.AddField(
            model_name='perfume',
            name='mainaccord2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfume',
            name='mainaccord3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfume',
            name='mainaccord4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfume',
            name='mainaccord5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfume',
            name='perfumer1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='perfume',
            name='perfumer2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='perfume',
            name='rating_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='perfume',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='perfume',
            name='year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='brand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
