# Generated by Django 5.2.7 on 2025-10-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0002_rename_notes_base_perfume_base_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
