# Generated by Django 5.2.7 on 2025-10-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0003_perfume_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
