# Generated by Django 5.2.7 on 2025-10-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0005_perfume_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='perfumes/'),
        ),
    ]
