# Generated by Django 5.2.7 on 2025-10-28 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0006_alter_perfume_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfume',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='perfume',
            name='brand',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='mainaccord1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='mainaccord2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='mainaccord3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='mainaccord4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='mainaccord5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='rating_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='rating_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
