# Generated by Django 5.2.7 on 2025-10-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0007_remove_perfume_image_url_alter_perfume_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
